// Copyright 2022 Gravitational, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.34.1
// source: certs.proto

package proto

import (
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Set of certificates corresponding to a single public key.
type Certs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SSH certificate marshaled in the authorized key format.
	SSH []byte `protobuf:"bytes,1,opt,name=SSH,proto3" json:"SSH,omitempty"`
	// TLS X.509 certificate (PEM-encoded).
	TLS []byte `protobuf:"bytes,2,opt,name=TLS,proto3" json:"TLS,omitempty"`
	// TLSCACerts is a list of TLS certificate authorities.
	TLSCACerts [][]byte `protobuf:"bytes,3,rep,name=TLSCACerts,proto3" json:"TLSCACerts,omitempty"`
	// SSHCACerts is a list of SSH certificate authorities.
	SSHCACerts    [][]byte `protobuf:"bytes,4,rep,name=SSHCACerts,proto3" json:"SSHCACerts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Certs) Reset() {
	*x = Certs{}
	mi := &file_certs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Certs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Certs) ProtoMessage() {}

func (x *Certs) ProtoReflect() protoreflect.Message {
	mi := &file_certs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Certs.ProtoReflect.Descriptor instead.
func (*Certs) Descriptor() ([]byte, []int) {
	return file_certs_proto_rawDescGZIP(), []int{0}
}

func (x *Certs) GetSSH() []byte {
	if x != nil {
		return x.SSH
	}
	return nil
}

func (x *Certs) GetTLS() []byte {
	if x != nil {
		return x.TLS
	}
	return nil
}

func (x *Certs) GetTLSCACerts() [][]byte {
	if x != nil {
		return x.TLSCACerts
	}
	return nil
}

func (x *Certs) GetSSHCACerts() [][]byte {
	if x != nil {
		return x.SSHCACerts
	}
	return nil
}

var File_certs_proto protoreflect.FileDescriptor

const file_certs_proto_rawDesc = "" +
	"\n" +
	"\vcerts.proto\x12\x05proto\x1a\x14gogoproto/gogo.proto\"\xc9\x01\n" +
	"\x05Certs\x12#\n" +
	"\x03SSH\x18\x01 \x01(\fB\x11\xea\xde\x1f\rssh,omitemptyR\x03SSH\x12#\n" +
	"\x03TLS\x18\x02 \x01(\fB\x11\xea\xde\x1f\rtls,omitemptyR\x03TLS\x12:\n" +
	"\n" +
	"TLSCACerts\x18\x03 \x03(\fB\x1a\xea\xde\x1f\x16tls_ca_certs,omitemptyR\n" +
	"TLSCACerts\x12:\n" +
	"\n" +
	"SSHCACerts\x18\x04 \x03(\fB\x1a\xea\xde\x1f\x16ssh_ca_certs,omitemptyR\n" +
	"SSHCACertsB@\xc8\xe1\x1e\x00\xc8\xe2\x1e\x01\xd0\xe2\x1e\x01Z2github.com/gravitational/teleport/api/client/protob\x06proto3"

var (
	file_certs_proto_rawDescOnce sync.Once
	file_certs_proto_rawDescData []byte
)

func file_certs_proto_rawDescGZIP() []byte {
	file_certs_proto_rawDescOnce.Do(func() {
		file_certs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_certs_proto_rawDesc), len(file_certs_proto_rawDesc)))
	})
	return file_certs_proto_rawDescData
}

var file_certs_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_certs_proto_goTypes = []any{
	(*Certs)(nil), // 0: proto.Certs
}
var file_certs_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_certs_proto_init() }
func file_certs_proto_init() {
	if File_certs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_certs_proto_rawDesc), len(file_certs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_certs_proto_goTypes,
		DependencyIndexes: file_certs_proto_depIdxs,
		MessageInfos:      file_certs_proto_msgTypes,
	}.Build()
	File_certs_proto = out.File
	file_certs_proto_goTypes = nil
	file_certs_proto_depIdxs = nil
}
